export const FIELD_VALUES = {
  type: [
    "Anthropologist",
    "Architect",
    "Art Critic",
    "Author or Publisher",
    "Biographer",
    "Chef or Food Writer",
    "Economist",
    "Engineer or Technologist",
    "Entertainer",
    "Entrepreneur",
    "Executive",
    "Historian or Philosopher",
    "Investor",
    "Journalist",
    "Librarian or Teacher",
    "Musician or Filmmaker",
    "Product Manager or Designer",
    "Scientist"
  ],
  genres: [
    "Biography",
    "Business",
    "Children",
    "Classic",
    "Economics",
    "Fantasy",
    "Fiction",
    "Historical",
    "History",
    "Horror",
    "Memoir",
    "Misc",
    "Mystery",
    "Nonfiction",
    "Philosophy",
    "Poetry",
    "Politics",
    "Romance",
    "Science",
    "Science Fiction",
    "Self-Help",
    "Young Adult"
  ]
} as const;
