import { Book, Person } from "@/types";

export const FIELD_VALUES = {
  type: [
    "Engineer or Technologist",
    "Entertainer",
    "Entrepreneur",
    "Executive",
    "Investor",
    "Product Manager or Designer",
    "Anthropologist",
    "Architect",
    "Art Critic",
    "Author or Publisher",
    "Biographer",
    "Chef or Food Writer",
    "Economist",
    "Historian or Philosopher",
    "Journalist",
    "Librarian or Teacher",
    "Musician or Filmmaker",
    "Scientist"
  ],
  genres: [
    "Biography",
    "Business",
    "Fiction",
    "Classic",
    "Economics",
    "Fantasy",
    "Memoir",
    "Mystery",
    "Nonfiction",
    "History",
    "Science",
    "Science Fiction",
    "Philosophy",
    "Poetry",
    "Politics",
    "Romance",
    "Horror",
    "Children",
    "Self-Help",
    "Young Adult",
  ],
} as const;
